### ISSUE TITLE
Feature request: Weighted inputs

### ISSUE THREAD

**Issue by MickTheMechanic** [denyssene/SimpleKalmanFilter#11]
I would like to request a new feature.

It would be nice to have a version that accepts two values, the value to be filtered, and the values weight. 

The weight is used as a means to tell the filter how much influence the current value should have on the next estimate.

Is this something we can implement?

**Comment by MickTheMechanic** [comment]
Perhaps something like this?

float SimpleKalmanFilter::updateEstimate(float mea, float weight)
{
  // Ensure weight is within bounds [0, 100]
  weight = std::max(0.0f, std::min(weight, 100.0f));

  // Adjust _q based on weight, assuming _q is initially set for a weight of 100
  float adjusted_q = _q * (weight / 100.0f);

  _kalman_gain = _err_estimate / (_err_estimate + _err_measure);
  _current_estimate = _last_estimate + _kalman_gain * (mea - _last_estimate);
  _err_estimate = (1.0f - _kalman_gain) * _err_estimate + fabsf(_last_estimate - _current_estimate) * adjusted_q;
  _last_estimate = _current_estimate;

  return _current_estimate;
}

**Comment by denyssene** [comment]
Interesting proposal, but I understand it extrapolates the scope of this tiny library. It's something that should be done with inheritance or a decorator class.
