### ISSUE TITLE
Please post a release for v 0.1.1

### ISSUE THREAD

**Issue by drf5n** [denyssene/SimpleKalmanFilter#12]
The repository has a code version of 0.1.1, but Arduino Library manager won't share it until you post a 0.1.1 release on https://github.com/denyssene/SimpleKalmanFilter/releases

See:

#5

and 

https://github.com/denyssene/SimpleKalmanFilter/commit/ed717000b1e57e7fee8f7e5e0fd2d9d459d72847

**Comment by denyssene** [comment]
Preparing the 0.2 Release
