### ISSUE TITLE
Change the "Always start at 0" behaviour?

### ISSUE THREAD

**Issue by EdJoPaTo** [denyssene/SimpleKalmanFilter#2]
With the current behaviour the Filter starts at 0. This results in a high error estimate at the beginning.

What about setting the first value as the start value instead? the starting error estimate would have more impact then.

A possible implementation of this could be the following code. the Gain can never be 0 with a positive error in the measurement so this is only the case for the first value.
```c
float SimpleKalmanFilter::updateEstimate(float mea)
{
  if (_kalman_gain == 0.0) {
    _last_estimate = mea;
  }
  […]
}
```

Is this useful? Or do is miss something?

**Comment by denyssene** [comment]
Hello EdJoPaTo,

Makes sense. Anyway, it's usual to let the filter iterate few times before it stabilizes by itself.

**Comment by EdJoPaTo** [comment]
But the iteration process can be shortened when the area of values is known.
My current approach is to set the estimated error extremely high so it stabilizes faster. That feels wrong to me as it is just a „random“ big number in there. But maybe that’s what’s always done?

**Comment by NimaaZx** [comment]
Hey. I want to use it for BLE RSSI. As I figured out We have three Value. Real_Value (Real Value Without Noise)  - Measured_value(Real Value + Some Noisy Value)  - Estimated_value(Filtered Result) 
                                                                                                                                                                1- is Real Value is an Original Value ? what is supposed to be For RSSI Value?                                                  2- What is that is defined in first of example code ? "SimpleKalmanFilter simpleKalmanFilter(2, 2, 0.01);"

**Comment by denyssene** [comment]
changed in constructor

**Comment by level20peon** [comment]
> changed in constructor

Could you elaborate on where you changed this and how to set the initial filter value? I browsed through your commits but couldn't find anything related to this reply of yours.
