### ISSUE TITLE
Kalman for dummies

### ISSUE THREAD

**Issue by myval** [denyssene/SimpleKalmanFilter#3]
Hi,
I must say this was the best library I found in a while. Kalman filter is just what I was missing in my project. I have tried all sorts of averages moving averages IIR FIR but this filter is just superb at filtering noise while still having decent response time.
I am not really strong at this level of mathematics and I was wondering if you could explain fine tuning of this filter.
I just would like to know how the filter actually changes with change in those constants e_mea, q and if I understand correctly e_est don't have to worry about since the filter adjusts it anyway.
I can see that if I increase e_mea or decrease q the response is slower but I would love to be able to fine tune and understand how to fine tune the filter. Can you give me some sort of kalman filter for dummies info, please?
thank you
Josef

**Comment by denyssene** [comment]
Hello Josef,

Thank you for your kind words. I'm always glad to see that it's useful and appreciated for the community.
For a better understanding about how it works I recommend watching the first videos of this playslist:
https://www.youtube.com/watch?v=CaCcOwJPytQ&list=PLX2gX-ftPVXU3oUFNATxGXY90AULiqnWT
