### ISSUE TITLE
Stm32 bluepill support

### ISSUE THREAD

**Issue by TheSnowFall** [denyssene/SimpleKalmanFilter#8]
Hello,
Good day.
Does this library support STM32 blue pill? As Bluepill is a 32-bit MCU.
Please let me know.

**Comment by denyssene** [comment]
Yes, it's supposed to work fine. You can improve by changing all floats for double.

**Comment by denyssene** [comment]
Let me know if you have any issues. There are some new improvements I was planning to push.

**Comment by TheSnowFall** [comment]
Thanks for asking. I didn't find much issues.  Will let you know if I find something. You may push your library for now.
