### ISSUE TITLE
Question concerning err_estimate

### ISSUE THREAD

**Issue by Lecrapouille** [denyssene/SimpleKalmanFilter#9]
Hi! Compared to Professor Michel van Biezen lectures, in the following line:

https://github.com/denyssene/SimpleKalmanFilter/blob/ed717000b1e57e7fee8f7e5e0fd2d9d459d72847/src/SimpleKalmanFilter.cpp#L22

where this additional formula `+ fabsf(_last_estimate-_current_estimate)*_q` not explained by the Pr comes from? I remember when I tried Pr formulas, my Kalman did not succeed to filter high fluctuations in the signal, with this extra code it works.

Thanks!

**Comment by denyssene** [comment]
Check it here https://www.youtube.com/watch?v=CaCcOwJPytQ

**Comment by Kasimashi** [comment]
Same question here @denyssene where did you spot this formula ? Video (1st one at least) your provide didn't mention this. @Lecrapouille in copy :)
